### PR TITLE
Feature/octo 1077 add repair scheduler

### PR DESCRIPTION
**Pull request by igusher**
regular repairs enabled, 
regular backups disabled

### CODE REVIEW

**Comment by igusher** [comment]
Snapshots are re-enabled. I've disabled them for table feedbacks(aggregation job does some kind of backups) and indirectcontextitems (shall be restorable via other sources).

**Comment by s-soroosh** [comment]
@igusher Please have a look to nodetool repair as well.
I feel current repair process can lead us to inconsistency.

**Comment by igusher** [comment]
Yeah, that's true.
Actually not inconsistency,  rather simultaneous  repair will fail, but still...

**Comment by igusher** [comment]
Now it first tries to acquire log in etcd before doing repair

**Comment by s-soroosh** [comment]
👍

**Comment by igusher** [comment]
Successfuly ran through on each node.

**Pull request merged**
